### ISSUE TITLE
늦었지만 혹시 엠베스트 메인 화면에서 좌측 하단 연타할 시 나오는 인증번호 얻는 방식을 더 자세하게 알 수 있을까요

### ISSUE THREAD

**Issue by steamkbg0506** [seojun0924/mbest#1]
오랜만에 다시 엠베스트 탭 만져봅니다

**Comment by seojun0924** [comment]
네네 오랜만입니다

SHA로 암호화한 걸 6자리 자르는 원리입니다

연타한 화면에서 기기 시리얼을 주시면 1주일치 뽑아서 아직 되는지 확인해보는 게 좋겠습니다

**Comment by seojun0924** [comment]
꺼무위키에도 이게 올라갔더군요 ㅋㅋ

**Comment by seojun0924** [comment]
제가 앱을 안지웠군요

오늘내일자 마스터 키를 보내니 확인 바랍니다[Screenshot_20240317-225302_  .jpg](https://github.com/seojun0924/mbest/assets/106897282/7f83a472-f2a5-49f0-874b-74d29e8a3304)

**Comment by steamkbg0506** [comment]
빠른 답변 감사합니다
성능도 썩 시원찮아서 집에 굴러다니는 라즈베리파이 터치스크린으로 써야 될 것 같네요

**Comment by steamkbg0506** [comment]
아 날짜가 YYYYMMDD식으로 찍는 것이 아니라  YYYY(M)M(D)D식으로 찍는 것이였군요

**Comment by steamkbg0506** [comment]
혹시 실례되지 않는다면 저 앱 파일을 주실 수 있을까요

**Comment by steamkbg0506** [comment]
그리고 초기화 인증번호가 다르던데 혹시 그 번호의 규칙도 알고 있나요?

**Comment by seojun0924** [comment]
초기화 번호는 (시리얼값+날짜) 를 해쉬로 돌려야 가능합니다

해제 인증은 마스터키로 됩니다만 초기화 해제는 고유번호 (시리얼)로만 가능합니다

시리얼을 주시면 다시 드리겠습니다

**Comment by seojun0924** [comment]
앱 파일은.. mdm 건 기기에밖에 없어서..ㅠ 추출이 안됩니다

**Comment by seojun0924** [comment]
앗 아이고.. ㅋㅋ ㅠ

혹시 초기화 막히면 쓰셔요

![Screenshot_20240318-201455_  .jpg](https://github.com/seojun0924/mbest/assets/106897282/4cbfaf73-485a-4195-b0cb-d14f6a97f542)

**Comment by steamkbg0506** [comment]
혹 나중에 도움을 받으실 분들을 위하여:
 - 탭 기종은 Galaxy Tab Advanced2, SM-T583입니다.
 - 오딘은 sboot 패치된 3.13버젼을 이용하였습니다.
 - 순정 펌웨어는 samfw.com에서 다운로드받았습니다.
 - 다운로드 모드는 볼륨업 + 볼륨다운키를 누른 상태에서 USB 케이블을 연결해 진입하였습니다.
큰 도움 주신 seojun0924님 감사합니다
