### ISSUE TITLE
엠베스트 프라임탭 인증코드 관련 내용 자세하게 알고 싶습니다.

### ISSUE THREAD

**Issue by neollu75** [seojun0924/mbest#2]
제 형님께서 자꾸 학교에 얼마전 구매한 A9+ 를 들고가는 바람에 제가 집에서 급하게 사용할 태블릿이 없어 엠베스트 태블릿을 이용해 보려 하는데, 인증코드 관련 내용이 잘 이해가 안갑니다.

인증코드가 불가능하더라도 한번 뚫어보고 싶네요.
탭 기종은 SM-T583 Advanced2입니다.
혹시나 도움이 될 만한 정보를 알려드리자면,
탭에 한번 오류가 크게 나서 최근에 고객센터 통해 초기화 받은 뒤 프로그램 재설치를 하는 과정에서 Nearby Share가 아닌 (구글) Quick Share로 변경되었고, Polaris Office앱은 엠베스트 PDF 앱으로 대체되었습니다.
현재 약정이 남아있는데, 인증코드를 통해 앱에서 나간다면 불이익이 생길 수 있는걸까요?

**Comment by seojun0924** [comment]
1. 인증코드 생성은 시리얼 넘버로 가능합니다. 코드를 주시면 알려드리겠습니다.
2. 자유로이 인증코드를 이용해 오가셔도 약정 관련 불이익은 3.0.213 기준 없습니다. 인증코드 이용한 일반 탭 전환 후, 엠베스트 앱 접속 시 정상적 이용이 가능합니다.

**Comment by neollu75** [comment]
1. 이메일 있으실까요? 시리얼 넘버이다 보니 조금 조심하게 되네요.
2. 좌측 하단 연타 시 나오는 화면에서 진입 이력 확인 메뉴가 있었던 던 것은데, 나중에 고장이나 오류 발생 시 엠베스트 학습지원센터에서 진입 이력 확인 후에 진입 이력이 있는것을 확인하고 사용자 과실이라 할 수 있는것은 아닌지요?

감사합니다.

**Comment by seojun0924** [comment]
1. seojun2343@naver.com입니다.
2. 진입 이력 메뉴에서 제가 사용하던 버전 (3.0.213)에서는 그 메뉴가 실질적 기능이 없었습니다. 코드상에도 없었고, 몇 번을 사용해도 실제 효과가 없었습니다만...
3. 인증 코드 사용이 신경쓰이신다면, 인증 코드 대신 ProKiosk 모드를 Wi-Fi 설정을 연 채로 `dpaqpt01` 비밀번호로 나간 후 ADB를 이용해 엠베스트를 끄는 방법이 있습니다만 인증 코드가 훨씬 편리합니다

**Comment by neollu75** [comment]
시리얼 코드 이메일 전송했습니다.
제 이메일 주소는 neollu75@gmail.com입니다.
코드가 매일매일 바뀌는 거는 어떻게 해서 알 수 있을까요?

**Comment by seojun0924** [comment]
![Screenshot_20240626-213153_  .jpg](https://github.com/seojun0924/mbest/assets/106897282/30928759-0236-40ad-a1af-9a09cca19f86)

이렇게 있습니다.

**Comment by neollu75** [comment]
감사합니다.
7월 2일 이후 건은 정확히 어떻게 해야 인증 코드 확인이 가능한지 설명 해 주실 수 있나요?
`엠베스트 메인 화면에서 좌측 하단 7회 연타 시 나오는 인증 코드 화면의 인증번호는 '시리얼 + 날짜'에다 sha로 암호화해서 6자를 떼내고 /를 제거한 다음에 regex로 대문자로 치환한 코드` 내용이 정확히 이해가 가지 않습니다.
R54########202473 을 SHA-1로 암호화한뒤 앞 6자리만 이용해 뒤 작업을 하는건가요?

**Comment by neollu75** [comment]
![Screenshot_20240627-014955_Settings](https://github.com/seojun0924/mbest/assets/162023843/4335d738-ab43-4f11-a642-42e5bf6e6e11)
추가로, 설정을 찾아보다 com.samsung.android.**dqagent**_SA_SDK 인증서를 발견했는데, 이 인증서는 프라임탭 앱과 어떤 관계인지 알고 싶습니다.

**Comment by seojun0924** [comment]
네 7월 3일은 <시리얼>202473을 SHA 작업을 한 후에 /를 없애고 ->6자를 떼낸 후 regex를 이용해 소문자를 대문자로 만듭니다

dqagent는 삼성의 device quality agent로 엠베스트 자체와는 별 상관 없는 갈로 알고 있습니다

SHA 몇인지는 기억이 잘 나지 않습니다.. 소스를 볼 수 있으면 보고 오겠습니다

**Comment by seojun0924** [comment]
그리고 차라리 adb를 이용해 klmsagent를 죽이고 원격제어를 다른 앱으로 바꿔치기하시는게 나을 거 같습니다

레포 루트에 올려 두겠습니다

**Comment by seojun0924** [comment]
ADB를 켜서 com.samsung.klmsagent를 disable-user으로 죽인 뒤 애니서포트를 지워 주시고, 그 후 루트에 있는 앱을 설치하신 뒤 klmsagent를 enable로 켜 주시면 됩니다

**Comment by neollu75** [comment]
> klmsagent를 enable로 켜 주시면 됩니다

죄송합니다.. adb를 LG폴더폰에 앱 설치할때만 사용해 보아서 adb 지식이 많이 없습니다. adb shell pm disable-user --user 0 com.samsung.klmsagent 해당 명령어가 맞는지 확인 부탁드리겠습니다.
추후에 원격 지원이 필요할 때에는 어떻게 하면 되는 지 궁금합니다.

**Comment by neollu75** [comment]
adb로 원격지원 앱 삭제를 시도해 보았으나 반응이 없고 삭제가 안됩니다.
KLMS 비활성화 해서 원격지원 앱 실행은 되지 않습니다.
어떻게 해야 삭제가 가능할까요?

**Comment by seojun0924** [comment]
얼추 맞습니다.

1. 활성화 시 그냥 enable입니다.
2. 원격 지원 삭제 시 disable-user net.koino.anysupportMobile 명령어가 선행되어야 합니다.
3. 해당 앱에 나가는 API가 있어서 원격지원이 필요할 일은 거의 없습니다만 그런 일이 생긴다면 엠베스트를 나간 후 그 앱을 지워 주시면 원격지원이 자동 설치됩니다.

**Comment by seojun0924** [comment]
원격 지원을 disable-user한 후 pm uninstall net.koino.anysupportMobile로 지우시면 됩니다

**Comment by neollu75** [comment]
shell에서 pm uninstall net.koino.anysupportMobile 실행 시 `Failure [DELETE_FAILED_OWNER_BLOCKED]` 오류가 발생합니다.
pm uninstall --user 0 net.koino.anysupportMobile 실행 시에는 아무 처리도 되지 않고 shell에서 명령어 입력이 불가해집니다.
원격지원 앱 disable-user는 이미 한 상태입니다.

**Comment by neollu75** [comment]
![image](https://github.com/seojun0924/mbest/assets/162023843/3e7f67b8-5ea7-4be0-98df-9a5930cb5da1)
![image](https://github.com/seojun0924/mbest/assets/162023843/d7422611-2908-4dbf-bc98-2f582c93de83)
사진 첨부합니다.
2번째 이미지 같은 경우 명령어 실행 후 시간이 지나도 gtaxladwifikx:/ $가 shell에 표시되지 않으며, 원격지원 앱도 삭제되지 않습니다.
webadb에서 하던 구글에서 직접 받은 platform-tools로 하던 나오는 건 똑같습니다.

**Comment by neollu75** [comment]
![image](https://github.com/seojun0924/mbest/assets/162023843/e3011a36-1a90-4411-aa09-1549f6173c75)
logcat 정보도 첨부합니다. pm uninstall -k --user 0 net.koino.anysupportmobile 실행 결과입니다.

**Comment by seojun0924** [comment]
dumpsys device_policy를 보여주시면 감사하겠습니다

**Comment by neollu75** [comment]
[pol.txt](https://github.com/user-attachments/files/16027098/pol.txt)
이거 말씀하시는 거 맞으실까요?

**Comment by neollu75** [comment]
네 위에서 알려주신 인증 코드로 엠베스트 종료 후 진행 했을 때 결과입니다.

**Comment by seojun0924** [comment]
기기 관리자 애플리케이션 중 목록에 아무 것도 뜨지 않으며 해제도 되지 않는 게 있나요?

**Comment by neollu75** [comment]
> 기기 관리자 애플리케이션 중 목록에 아무 것도 뜨지 않으며 해제도 되지 않는 게 있나요?

이해가 가지 않습니다. 목록에 아무 것도 없는데 해제가 되지 않는다는게 어떤 말씀이신가요?
(그냥 해제가 안되는 거는 프라임탭 서포트와 엠베스트 프라임탭 앱이 있습니다.)

**Comment by neollu75** [comment]
서포트가 아니라 업데이트 에이전트였네요

**Comment by seojun0924** [comment]
눌러 들어갔을 때 이렇게 생긴 것입니다.

비슷한 문구 (관리자가..) 가 씌여 있고, 삭제/해제 버튼도 비활성화되어 있습니다.

![Screenshot_20240628-225543_Settings.jpg](https://github.com/seojun0924/mbest/assets/106897282/bcce9871-40df-49e4-942b-ef457d6375cf)

**Comment by neollu75** [comment]
프라임탭 앱과 Update Agent는 모두 삭제/해제 버튼이 비활성화 되어 있으나, 관리자가~ 내용 아래에 아무것도 없는 앱은 없습니다.

**Comment by neollu75** [comment]
전에 제가 프라임탭에 오류가 발생해서 고객지원 통해 초기화를 진행했었다고 말씀드렸었는데요, 그때 제가 직접 크롬으로 엠베스트 사이트에서 애니서포트 apk를 다운받고 설치해서 원격지원으로 프라임탭 설치를 받았습니다.
이게 현재 문제와 관련이 있는 지는 모르겠으나 일단 알려드려봅니다.

**Comment by neollu75** [comment]
원격지원 앱 말고도, 오디오 자료실도 똑같은 현상이 있네요.
apk로 설치했던건 관련이 없는 것 같습니다.

**Comment by neollu75** [comment]
프라임탭 자체에서 원격지원 삭제 시도 시에 기기 관리자가 사용하는 앱이여서 삭제가 안된다고 알림이 뜨네요.
전에 첨부한 사진처럼 기기 관리자 앱 목록에는 원격지원 앱이 없기에 프라임탭 앱 기기 관리자를 해제해야 원격지원 삭제가 될 것 같은데 해제가 불가능합니다.
해제 방법이 없을까요?

**Comment by seojun0924** [comment]
제가 가지고 있던 녹스 라이선스가 날아간 게 좀 크네요. 그와 별개로 프라임탭도 업데이트를 해 버린 모양입니다. 그래도 방법은 있으니 다행입니다.

`pm disable-user kr.co.mbest.smartlearningtab && pm enable kr.co.mbest.smartlearningtab && pm uninstall net.koino.anysupportMobile` 명령어 (원라이너입니다) 로 사용한 후 엠베스트 기기 관리자를 켜 주시면 됩니다.

**Comment by neollu75** [comment]
> 제가 가지고 있던 녹스 라이선스가 날아간 게 좀 크네요. 그와 별개로 프라임탭도 업데이트를 해 버린 모양입니다. 그래도 방법은 있으니 다행입니다.
> 
> `pm disable-user kr.co.mbest.smartlearningtab && pm enable kr.co.mbest.smartlearningtab && pm uninstall net.koino.anysupportMobile` 명령어 (원라이너입니다) 로 사용한 후 **엠베스트 기기 관리자를 켜 주시면** 됩니다.

엠베스트 프라임탭 앱 기기 관리자를 끈다는 의미인가요?
이미 프라임탭 앱은 기기 관리자에 포함되어 있습니다.

**Comment by neollu75** [comment]
일단 삭제는 Success 떴습니다.

**Comment by neollu75** [comment]
신기하게도 보이지 않던 엠베스트 앱들이 앱스화면에 주루룩 나오네요

**Comment by seojun0924** [comment]
그 부분들은 설치한 앱으로 나갔을 때만 사용 가능합니다. 엠베스트 시작 시마다 정책 설정을 하는지라 사용이 매우 까다로워 거의 힘듭니다.

**Comment by neollu75** [comment]
지금 해보니 앱에서 엠베스트 프라임탭 DA 해제 허용 후 기기관리자 해제하니 보안정책이 해제되어 Wi-Fi 다이렉트, USB 호스트 저장공간 등 모두 사용 가능한 것 같습니다.

**Comment by seojun0924** [comment]
잘 되셨다니 다행입니다 :)

**Comment by neollu75** [comment]
네. 엠베스트에서 다시 업데이트를 하지 않는 한 더이상 여쭈어 볼 것은 없을 것 같습니다.(SHA는 제가 할수 있는 해쉬 다 돌려봐도 안나오는군요)
저는 이만 여기서 떠나보도록 하겠습니다.
감사합니다.

추가로, 추후에 관련 내용을 찾으실 분을 위해서 아래에 파일 하나를 남겨놓겠습니다. 다 정리해 놓았습니다.
[엠베스트 프라임탭 해제.pdf](https://github.com/user-attachments/files/16045275/default.pdf)
