### ISSUE TITLE
혹시 인증번호 알 수 있을까요

### ISSUE THREAD

**Issue by hongjun123-19** [seojun0924/mbest#4]
인증번호를 여러번 시도해 봐도 일치하지 않는다고만 뜨네요 혹시 시리얼 번호를 보내드려도 될까요?

**Comment by neollu75** [comment]
인증번호가 매일매일 바뀌는 원리라서 @seojun0924 님이 현재 인증번호 툴을 가지고 계실 지를 모르겠는데 만약 가지고 계신다면 날짜별로 요청하신 뒤에 따로 인증번호 없이 해제할 수 있도록 설정 하시는게 좋겠네요

**Comment by seojun0924** [comment]
어우 여기 오랜만이네요.

시리얼 주시면 보내드리겠습니다

**Comment by hongjun123-19** [comment]
R9TT800F1HB입니다

**Comment by seojun0924** [comment]
![Screenshot_20241201-192112_  .jpg](https://github.com/user-attachments/assets/e8374297-6b8f-461b-8d0d-aac6e4798f78)
