### ISSUE TITLE
저도 도와주실 수 있나요?

### ISSUE THREAD

**Issue by LAME8620** [seojun0924/mbest#8]
R9TRA0B5JPJ가 인증코든데 sha256 하고 regex 했는데 안나오네요

**Comment by LAME8620** [comment]
![Uploading Screenshot_20241208_035518_Chrome Beta.jpg…]()

**Comment by LAME8620** [comment]
![Screenshot_20241208_035518_Chrome Beta](https://github.com/user-attachments/assets/10f88594-0ebb-484f-8a2c-e70b930424e9)

**Comment by seojun0924** [comment]
![Screenshot_20241208-173712_  .jpg](https://github.com/user-attachments/assets/d6601a5d-3a1f-4aa9-9b77-4e27df6e6810)

**Comment by LAME8620** [comment]
정말 감사합니다!!!

**Comment by neollu75** [comment]
> 참고: sha256해시를 hex가아닌 base64로 뽑아야된다네요

감사합니다. 수개월만에 미스테리가 풀렸네요.
https://ilovejua.tistory.com/3
위 변환기 이용하시면 간편하실듯 합니다.
시리얼 번호와 날짜 그대로 이어서 입력하시면 됩니다.(월과 일이 한자리수 일때 앞 0은 제거)
(예:시리얼이 R69D49210JF이고 날짜가 2024년 12월 9일일 때는 R69D49210JF2024129)
